### ISSUE TITLE
Homebridge stuck in bootloop with homebrige-liftmaster2 json error

### ISSUE THREAD

**Issue by dawger1** [luisiam/homebridge-liftmaster2#37]
Hi there,

I recently pulled oznu's latest homebridge image for raspberry pi, but for some reason, it dumped all of my plugins.  I re-installed the liftmaster2 plugin, and now my homebridge server seems to be stuck in a boot loop.  Here's what my log file shows when I restart my homebridge server:

> homebridge_1  | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
homebridge_1  | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
homebridge_1  | [2018-1-29 17:03:13] Loaded plugin: homebridge-dummy
homebridge_1  | [2018-1-29 17:03:13] Registering accessory 'homebridge-dummy.DummySwitch'
homebridge_1  | [2018-1-29 17:03:13] ---
homebridge_1  | [2018-1-29 17:03:15] Loaded plugin: homebridge-liftmaster2
homebridge_1  | [2018-1-29 17:03:15] Registering platform 'homebridge-liftmaster2.LiftMaster2'
homebridge_1  | [2018-1-29 17:03:15] ---
homebridge_1  | [2018-1-29 17:03:16] Loaded plugin: homebridge-nest
homebridge_1  | [2018-1-29 17:03:16] Registering platform 'homebridge-nest.Nest'
homebridge_1  | [2018-1-29 17:03:16] ---
homebridge_1  | [2018-1-29 17:03:17] Loaded plugin: homebridge-platform-wemo
homebridge_1  | [2018-1-29 17:03:17] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
homebridge_1  | [2018-1-29 17:03:17] ---
homebridge_1  | [2018-1-29 17:03:18] Loaded plugin: homebridge-config-ui-x
homebridge_1  | [2018-1-29 17:03:18] Registering platform 'homebridge-config-ui-x.config'
homebridge_1  | [2018-1-29 17:03:18] ---
homebridge_1  | [2018-1-29 17:03:18] Loaded config.json with 0 accessories and 3 platforms.
homebridge_1  | [2018-1-29 17:03:18] ---
homebridge_1  | [2018-1-29 17:03:19] Loading 3 platforms...
homebridge_1  | [2018-1-29 17:03:19] [WeMo Platform] Initializing BelkinWeMo platform...
homebridge_1  | [2018-1-29 17:03:19] [MyQ] Initializing LiftMaster2 platform...
homebridge_1  | [2018-1-29 17:03:19] [Nest] Initializing Nest platform...
homebridge_1  | [2018-1-29 17:03:19] [Nest] Fetching Nest devices.
homebridge_1  | [2018-1-29 17:03:19] Loading 0 accessories...
homebridge_1  | [2018-1-29 17:03:19] [WeMo Platform] Online: Living Room Lights [6038E0496D48]
homebridge_1  | [2018-1-29 17:03:19] [WeMo Platform] Online: Kitchen Lights [6038E04B2A04]
homebridge_1  | [2018-1-29 17:03:19] [WeMo Platform] Online: Kitchen Table Lights [149182D8C390]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Upstairs Christmas Lights [58EF68D9EE70]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Dining Room Lights [149182D865E4]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Front Room Lights [149182CCA07C]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Davids Lamp [6038E05BA710]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Front Room Christmas Lights [58EF68D9FCC8]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Playroom Lamp [6038E05BB254]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Front Porch and Garage Lights [149182505F6C]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Online: Main Floor Bathroom Lights [149182D88550]
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Living Room Lights - Get state: On
homebridge_1  | [2018-1-29 17:03:20] [WeMo Platform] Davids Lamp - Get state: On
homebridge_1  |
homebridge_1  | /homebridge/node_modules/homebridge-liftmaster2/index.js:249
homebridge_1  |       var json = JSON.parse(body);
homebridge_1  |                       ^
homebridge_1  | SyntaxError: Unexpected token < in JSON at position 0
homebridge_1  |     at JSON.parse (<anonymous>)
homebridge_1  |     at Request._callback (/homebridge/node_modules/homebridge-liftmaster2/index.js:249:23)
homebridge_1  |     at Request.self.callback (/homebridge/node_modules/request/request.js:186:22)
homebridge_1  |     at emitTwo (events.js:126:13)
homebridge_1  |     at Request.emit (events.js:214:7)
homebridge_1  |     at Request.<anonymous> (/homebridge/node_modules/request/request.js:1163:10)
homebridge_1  |     at emitOne (events.js:116:13)
homebridge_1  |     at Request.emit (events.js:211:7)
homebridge_1  |     at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1085:12)
homebridge_1  |     at Object.onceWrapper (events.js:313:30)
homebridge_1  |     at emitNone (events.js:111:20)
homebridge_1  |     at IncomingMessage.emit (events.js:208:7)
homebridge_1  |     at endReadableNT (_stream_readable.js:1055:12)
homebridge_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
homebridge_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)

Can somebody please help me fix this?

**Comment by dawger1** [comment]
Update: I tried uninstalling the plugin and clearing my config.json files.  The homebridge server now starts normally, and everything else seems fine.  As soon as I re-install Liftmaster2 and re-add my config.json details, I end up with the same error messages at startup.

**Comment by dawger1** [comment]
I'm not sure how I did it, but after removing and installing the plugin a number of times, I just re-installed the plug-in, and all appears to be well again.

**Comment by tkundhi** [comment]
I am having this same error. I've removed and reinstalled the plug-in multiple times without success. The only change is the information in the log. Usually it doesn't have the details. See example 1. However occasionally it has the same exact details as posted by @dawger1 . See example 2.

Any help is appreciated.

=======================================
Example 1 - occurs most often but contains no details except for same file and line number.
=======================================
raspberrypi homebridge[25073]:       var json = JSON.parse(body);
raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

=======================================
Example 2 - rare example has detail
=======================================
raspberrypi homebridge[22358]: /usr/lib/node_modules/homebridge-liftmaster2/index.js:249
raspberrypi homebridge[22358]:       var json = JSON.parse(body);
raspberrypi homebridge[22358]:                       ^
raspberrypi homebridge[22358]: SyntaxError: Unexpected token < in JSON at position 0
raspberrypi homebridge[22358]:     at JSON.parse (<anonymous>)
raspberrypi homebridge[22358]:     at Request._callback (/usr/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
raspberrypi homebridge[22358]:     at Request.self.callback (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
raspberrypi homebridge[22358]:     at emitTwo (events.js:126:13)
raspberrypi homebridge[22358]:     at Request.emit (events.js:214:7)
raspberrypi homebridge[22358]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1163:10)
raspberrypi homebridge[22358]:     at emitOne (events.js:116:13)
raspberrypi homebridge[22358]:     at Request.emit (events.js:211:7)
raspberrypi homebridge[22358]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1085:12)
raspberrypi homebridge[22358]:     at Object.onceWrapper (events.js:313:30)
raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by zjensen** [comment]
Alright finally figured it out. The only version of this package that is published is `0.1.0`, which has the json error mentioned above. So by default, adding this plugin through homebridge will pull from npm and install the broken version.

To fix this, go to your `package.json`, and run:
`npm install -save git+https://github.com/luisiam/homebridge-liftmaster2.git`

This will install the correct version of this package.

**Comment by tkundhi** [comment]
@zjensen I'm new to this so excuse my silly questions. I'm having problems installing non published plugins. I need to install the plugin globally because my homebridge is setup to autostart on boot via systemd, running on a Raspberry Pi 3. Appears to be a local error related to permissions. Here is the error.  

sudo npm install -g -save git+https://github.com/luisiam/homebridge-liftmaster2.git
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/luisiam/homebridge-liftmaster2.git /root/.npm/_cacache/tmp/git-clone-3d9ddf67
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-3d9ddf67': Permission denied

I've tried installing via my homebridge user and get the same error. Any suggestions?

**Comment by tkundhi** [comment]
@zjensen thanks! That worked. My status issues are resolved. The Garage Door is now showing in HomeKit. No need to me to purchase the Chamberlain HomeKit bridge for now. Works from Home and and via Siri.

**Comment by smshapiro85** [comment]
I would just like to report that zjensen's solution worked for me as well. All I did was uninstall and then reinstall using his command:
`npm install -save git+https://github.com/luisiam/homebridge-liftmaster2.git`

**Comment by danhausman** [comment]
try and fix permissions first

sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

Then install using this command:

sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git

**Comment by amitgir** [comment]
Started getting a similar issue. Here's the output:

```
[5/30/2019, 12:51:54 PM] SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Request._callback (/usr/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
at Request.self.callback (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:185:22)
at Request.emit (events.js:196:13)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1161:10)
at Request.emit (events.js:196:13)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:284:20)
at IncomingMessage.emit (events.js:201:15)
at endReadableNT (_stream_readable.js:1130:12)
[5/30/2019, 12:51:54 PM] Got SIGTERM, shutting down Homebridge...
```

Worked for for 2 months then stopped today. Maybe Liftmaster/Chamberlain changed something?

**Comment by dkhaley** [comment]
Like amitgir, I had this working and it stopped working today (30 May 2019). I get the exact same error messages as above.

Does anybody still have this working?

**Comment by danhausman** [comment]
Mine seems to be working fine. You might want to reboot your myq, I would also try and force your public facing IP address at home to change.  I get mine to do that by changing the Mac address fo the router plugged into my modem. They blacklisted my ip once, all I had to do was change my ip and it started working again. 

Dan

**Comment by amitgir** [comment]
I reinstalled the package using "npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git" rather than via the Config UI plugin and now all works. For some reason the npm command is pulling an outdated version like someone had mentioned above.
